name: Build and release

on:
  push:
    branches: [ main ]
    paths:
    - 'cv/**'
  pull_request:
    branches: [ main ]

env:
  zip-name: cv

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build pdf
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: cv
        root_file: |
          cv-ru.tex
        latexmk_use_lualatex: true

    - name: Upload pdf
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.zip-name }}
        path: |
          cv/cv-ru.pdf

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [build]
    steps:

      # This is a hack for bash-commands and memorize their output
      - name: Variables
        id: vars
        # `echo` in this format will allow you to subsequently reference the results
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
          echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.zip-name }}

      - name: Create release
        uses: softprops/action-gh-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cv-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha8 }}
          release_name: Documents (version ${{ steps.vars.outputs.date }})
          draft: false
          prerelease: false

      - name: Upload pdf
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./*.pdf
          tag: cv-${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha8 }}
          overwrite: true
          file_glob: true
